name: reenu_susan_kurian_112033_s_application1
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.0
  carousel_slider: ^4.0.0
  flutter_svg: ^2.0.9
  intl: ^0.18.0
  smooth_page_indicator: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  get_it: ^7.6.0
  watch_it: ^1.0.3
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app icon.png"
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Space Grotesk
      fonts: 
        - asset: assets/fonts/SpaceGroteskBold.ttf
          weight: 700
        - asset: assets/fonts/SpaceGroteskRegular.ttf
          weight: 400
