// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3VzZT24-IKfUm0QR3ECOV45_0EsKhrDE',
    appId: '1:1023510013619:web:8d097b6343f3aab621f2c6',
    messagingSenderId: '1023510013619',
    projectId: 'safenest-2a933',
    authDomain: 'safenest-2a933.firebaseapp.com',
    storageBucket: 'safenest-2a933.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa6nIhgahyAhTZl9hUSAsrD3WsFRLEg68',
    appId: '1:1023510013619:android:55ef24b2214e824e21f2c6',
    messagingSenderId: '1023510013619',
    projectId: 'safenest-2a933',
    storageBucket: 'safenest-2a933.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2zvmmt3rmFSBPUvxDaiZ5Q-mZreFj5KU',
    appId: '1:1023510013619:ios:48ba332f0c87285721f2c6',
    messagingSenderId: '1023510013619',
    projectId: 'safenest-2a933',
    storageBucket: 'safenest-2a933.appspot.com',
    iosBundleId: 'com.reenususankuriansapplication.app.testProject',
  );
}
